export enum Specialization {
  CARDIOLOGIST = 'CARDIOLOGIST',
  DERMATOLOGIST = 'DERMATOLOGIST',
  PEDIATRICIAN = 'PEDIATRICIAN',
  NEUROLOGIST = 'NEUROLOGIST',
  ORTHOPEDIC = 'ORTHOPEDIC',
  GENERAL_PHYSICIAN = 'GENERAL_PHYSICIAN',
  GYNECOLOGIST = 'GYNECOLOGIST',
  PSYCHIATRIST = 'PSYCHIATRIST',
}
